---
- name: Check users with password to get expired in 10 days
  hosts: all
  tasks:

  - name: Copy file to destination
    win_template:
      src: ./Get-PasswordExpirationDate.j2
      dest: C:\temp\Get-PasswordExpirationDate.ps1

  - name: Execute Powershell script
    win_shell: Get-PasswordExpirationDate.ps1
    args:
      chdir: C:\temp
    register: output

  - debug: var=output
