---
- name: Check users with password to get expired in 10 days
  hosts: all
  tasks:

  - name: Copy file to destination
    win_template:
      src: ./Get-PasswordExpirationDate.j2
      dest: C:\temp\Get-PasswordExpirationDate.ps1

  - name: Add function to Powershell
    win_shell: . .\Get-PasswordExpirationDate.ps1
    args:
      chdir: C:\temp

  - name: Using the Password Expiration Date Function
    win_shell: Get-PasswordExpirationDate
    register: output

  - debug: var=output.stdout_lines
